Test case "ramtest"
===================
Christoph Thelen <cthelen@hilscher.com>
:Author Initials: CT


[[About, About]]
== About

This document describes the RAM test for the Muhkuh test framework. The RAM test checks SDRAM devices with the random value test. The chapter <<Test_description>> discusses this method in detail.

The RAM test supports all existing netX chips with an SDRAM interface:

[horizontal]
netX500/100:: SDRAM on memory interface (MEM)
netx50:: SDRAM on memory interface (MEM)
netx10:: SDRAM on host interface (HIF)
netx51:: SDRAM on memory interface and host interface (MEM, HIF)
netx52:: SDRAM on host interface (HIF)


[[Test_description,Test description]]
== Test description

The core logic of the test is the random value approach. It fills the memory area with a pseudo random value stream.
"pseudo" means that the numbers are not real random values, but computed by a formula.
This means the "random" values are the same for every start of the program. Currently the formula is asciimath:[f(n)=a+n*b] for the asciimath:[n]-th value with prime numbers for asciimath:[a] and asciimath:[b].
Once the memory area is completely filled, the values are read back one after another. If a value is not the expected one, the process is stopped and the complete test case is marked as "failed".

The RAM test applies the random value approach multiple times:

- Repeat this for asciimath:[l] times:
  * Loop over 4 different pairs of prime numbers for asciimath:[a] and asciimath:[b]
  ** If enabled: run the random value test with 8 bit accesses to the memory
  ** If enabled: run the random value test with 16 bit accesses to the memory
  ** If enabled: run the random value test with 32 bit accesses to the memory
  ** If enabled: run the random value test with asciimath:[4*32] bit burst accesses to the memory

The program flow can be modified with a set of parameters:

- +loops+ defines the value for asciimath:[l].
- +checks+ selects the access types to the memory. It enables or disables the 8, 16, 32 and burst accesses.

The RAM test always starts at the beginning of the SDRAM device. The number of bytes to check from this position on can be configured with the parameter +size_exponent+.
It defines the number of bytes asciimath:[m] as asciimath:[m=2^text{size_exponent}].

[[Parameters, Parameters]]
== Parameters

+general_ctrl+::
  The complete value for the netX +general_ctrl+ register.
+timing_ctrl+::
  The complete value for the netX +timing_ctrl+ register.
+mr+::
  The complete value for the netX +mr+ register.
+size_exponent+::
  Check asciimath:[2^text{size_exponent}] bytes starting from the beginning of the SDRAM device.
+interface+::
  This is the interface where the RAM is connected. It
  must be either +MEM+ for the memory interface or +HIF+ for
  the host interface.
+checks+::
  This determines which checks to run. Select one or more
  values from this list and separate them with
  commata: +08BIT+, +16BIT+, +32BIT+ and +BURST+.
+loops+::
  The number of loops to run.

[TIP]
A good source for the parameters +general_ctrl+, +timing_ctrl+ and +mr+ is the +netx.xml+ file distributed with the Hilscher Bootwizard (http://www.hilscher.com/support_design.html?absenden=1&kat=5).

